version: '1'

services:
  gmail_service:
    build:
      context: ./gmail_api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network

  bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    depends_on:
      - gmail_service
    networks:
      - app_network

  agent: 
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports: 
      - "6000:6000"
    networks:
      - app_network 

networks:
  app_network:
    driver: bridge