services:
  gmail_service:
    build:
      context: ./gmail_api
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    networks:
      - app_network
    env_file:
      - ./gmail_api/.env

  bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    depends_on:
      - gmail_service
    networks:
      - app_network
    env_file:
      - ./telegram_bot/.env

  agent: 
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports: 
      - "6000:6000"
    networks:
      - app_network 
    env_file:
      - ./agent/.env

networks:
  app_network:
    driver: bridge